### ISSUE TITLE
USER STORY: Provide Products page showing all products

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#1]
## User Story:
As a **Customer** I want to **view all products** so that I can **browse through them and see what is available**

## Acceptance Criteria:
* Clicking on the All products link shows the customer all the products available to buy.
* Products should be rows of 3 on large screens.
* Products  should be stacked one on top of each other on small screens.

## Tasks:
- [x] Determine which products will be included in the site
- [x] Define product categories
- [x] Develop functionality to enable customer to view all products, 3 per row on large screens.
- [x] Develop functionality to enable the customer to view products by category.

## Bugs:
- [x] Images for the products are different sizes, need to resolve in CSS. Decided to cut the images to sizer re-submit to the app.
- [x] Background Image on index.html not appearing today.
