### ISSUE TITLE
USER STORY: Product Management

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#11]
## User Story: Product Management
As  **admin** I want to **be able to add new products, update existing products, and remove products from the app** so that I can **keep control of the product offering**

## Acceptance Criteria:
* Create an admin panel allowing for addition, editing and removal of products from the app.
* Admin panel is only accessible to a logged in admin user.
* Create templates to allow addition, removal and editing of products without going to admin panel.
* Product Management functionality can only be accessed by a logged in admin.

## Tasks:
- [x] Register data models in Django to create an admin panel.
- [x] Create super user to access the admin panel.
- [x] Create navigation to product management templates.
- [x] Create Product Management templates.
- [x] Use product management templates, confirm results in admin panel.
