### ISSUE TITLE
USER STORY: Respond to Queries

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#12]
## User Story:
As an **admin** I want to **respond promptly to customer enquiries** so that I can **respond quickly to customer needs and questions**

## Acceptance Criteria:
* Customer can create an enquiry and submit the enquiry
* Enquiry can be viewed by the admin in the admin panel
* Enquiry can be viewed by the admin in the app without using the admin panel
* Email confirmation sent to the customer
* Email sent to the admin telling the admin a new enquiry has been generated

## Tasks:
- [x] Create Enquiry data model and associated form
- [x] Generate message on screen to Customer that Enquiry has been submitted
- [x] Generate Email to customer that Enquiry has been submitted
- [x] Generate Email to admin detailing that enquiry has been submitted
- [x] Update the admin panel with new Enquiry
