### ISSUE TITLE
USER STORY: Add newsletter sign up capabaility

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#13]
As a site owner I want to have a facility that allows a user to subscribe to our site so that I can keep the customer informed about offers etc. 

### Tasks
- [x]  Select a subscriber service - MailChimp recommended
- [x] Add user option to main header bar, footer doesn't fit with site UX.

### Bugs
- [x] Deployed site crashed when code from mailchimp incorporated, found html, css and JS code through Chrome.
