### ISSUE TITLE
USER STORY: Product Detail

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#2]
## User Story:
As  **Customer** I want to **see product details when I select a product** so that I can **find out more about that product**

## Acceptance Criteria:
* When a customer selects a product , a product detail page appears
* The customer can return to home page from the product detail page
* The customer can return to the products page from the product detail page

## Tasks:
- [x] Develop html and CSS for the product detail page
- [x] Develop views and URLs to map the product detail page.
- [x] Enable customer to navigate around the site from the product detail page.
- [x] The product detail should include a product image, description, price.
