### ISSUE TITLE
USER STORY: As a customer, I want to be able to create an account and log in to the app.

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#3]
## User Story:
As  **Customer** I want to **log in and create an account** so that I can **have a more personal and secure experience in the app**

## Acceptance Criteria:
* User can log into the app, user is informed when log in is successful
* User can log out of the app, user is informed when logout is successful
* If the user has not already done so, the user is directed to register to create an account, user is informed when registration is successful

## Tasks:
- [x] Using Django allauth install the relevant functionality to control login/logout/registration
- [x] Create the login template
- [x] Create the logout template
- [x] Create the registration template
- [x] Implement messaging for above actions
