### ISSUE TITLE
USER STORY: Shopping Cart

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#4]
## User Story:
As  **Customer** I want to **add items to my shopping cart** so that I can **view the contents of my shopping cart**

## Acceptance Criteria:
* Selected items appear in the shopping cart.
* Associated prices appear in the shopping cart
* Total price for all items is available in shopping cart

## Tasks:
- [x] For the product detail, add an 'Add to Cart' button.
- [x] Add the product and product qty to the shopping cart
- [x] Update the total cart cost
- [x] Show the updated cart to the customer.
