### ISSUE TITLE
USER STORY: Shopping cart update line items

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#5]
## User Story:
As  **Customer** I want to **be able to update qty , add or remove line items form the shopping cart prior to making a purchase** so that I can **buy exactly what I want**

## Acceptance Criteria:
* Customer can add / remove line items, cart pricing will update.  Message confirming action is generated.
* Customer can adjust selected quantities, cart pricing will update. Message confirming action is generated.

## Tasks:
- [x] For each line item implement Add / Remove buttons, amend cart value, generate message to user.
- [x] For each line item, add functionality to adjust selected qty, amend cart value, generate message to user.

## Issues:
- [x] When the order qty was adjusted, the total price updated but not the line item price. Forgot to call adjust_item_qty and pass it qty and price.
