### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#6]
## User Story:
As  **customer** I want to **proceed to checkout and provide shipping and billing information** so that I can **get products delivered to a location that best suits me and pay online**

## Acceptance Criteria:
* User has access to a form requesting shipping address details.
* User can input credit card details to pay for the products.
* User gets payment success / payment failure messages as appropriate.

## Tasks:
- [x] Create shipping/ billing form.
- [x] Add field for credit card information
- [x] Implement STRIPE functionality
- [x] Implement webhooks to ensure no issues with interrupted / semi complete transactions.
- [x] Generate email to customer detailing order summary and order cost.

## Issues;
- [x] Webhooks returning an error, checking the endpoint is correct  - neede to make port public and include import stripe at top of webhook handler.
