### ISSUE TITLE
USER STORY: Order History

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#8]
## User Story:
As  **Customer** I want to **I want to view my order history** so that I can **see what I purchased in the past**

## Acceptance Criteria:
* Users profile setup
* View order history by user profile

## Tasks:
- [x] Develop user profile functionality
- [x] Develop template to display order history to user
- [x] User can only see own order history, another user cannot view the current users order history.
