### ISSUE TITLE
USER STORY: 

### ISSUE THREAD

**Issue by 2macs** [2macs/GardenCenter-PP5#9]
## User Story:
As  **Customer** I want to **the app to be visually appealing and user friendly** so that I can **focus on the shopping experience and not focus on navigating / using the app**

## Acceptance Criteria:
* Main navigation links are available on all pages
* Use of colors , fonts etc. are consistent across the site
* Use of graphics / images where possible to enhance the visual appeal of the site

## Tasks:
- [x] Create a base template , consistent across all pages.
- [x] Create std set of colors.
- [x] Seamless navigation around the site, products/cart etc. always available.
